# Jekyll configuration

name: Willy
description: 우리는 무엇인가를 진정으로 사랑한다면 그것을 소유하지 않아도 행복할 수 있다. 같은 하늘 아래 어딘가에 그것이 있다는 그 사실만으로도 가슴이 뛸 수 있는 것이다 - 철학 영화를 캐스팅 하다

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/qowns8.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
